site_name: Satriaana Documents
site_description: 'Satriaana Documents'
site_author: 'Team Satriaana'
docs_dir: docs/
repo_name: 'Satriaana/Documents'
repo_url: 'https://github.com/Satriaana/Documents'
nav:
    - Home: index.md
    - User Guide:
        - Overview: DevOps/roadmap.md
    
    
theme:
  name: 'mkdocs'
