site_name: Satriaana Documents
site_description: 'Satriaana Documents'
site_author: 'Team Satriaana'
docs_dir: docs/
repo_name: 'Satriaana/Documents'
repo_url: 'https://github.com/Satriaana/Documents'
nav:
    - Home: index.md
    - Teams:
        - Blog:
            - Roadmap: Blog/roadmap.md
        
        
        - Community Buildup:
            - Roadmap: Community Buildup/roadmap.md
        
        - Designing: 
            - Roadmap: Designing/roadmap.md
        
        - Developing:
            - Roadmap: Developing/roadmap.md
        
        
        - DevOps: 
           - Roadmap: DevOps/roadmap.md
           
        - Project Management: 
            - Roadmap: Project Management/roadmap.md

    
theme:
  name: 'mkdocs'
