site_name: Satriaana
site_url: https://satriaana.github.io/Documents/
site_description: Project documentation with Markdown.
site_author: Team Satriaana

repo_url: https://github.com/Satriaana/Documents/
edit_uri: ""

theme:
    name: mkdocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md


extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
 
copyright: Copyright &copy; 2021 <a href="https://satriaana.org">Team Satriaana</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Team Satriaana</a>.

plugins:
    - search
    - redirects:
        redirect_maps:
            user-guide/plugins.md: dev-guide/plugins.md
            user-guide/custom-themes.md: dev-guide/themes.md
            user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
